### ISSUE TITLE
cannot turn on the extension

### ISSUE THREAD

**Issue by suuuuz** [cschiller/zhongwen#2]
I tried closing and re-opening Chrome and resetting my computer, but I couldn't turn on the extension when I click it.

**Comment by cschiller** [comment]
What happens when you click on the icon? Do you see the red "On" label?

Also, when you go to chrome://extensions/ what version does it show for Zhongwen?

**Comment by suuuuz** [comment]
nothing happens when I click it

apparently I'm using the 5.1.1 version

**Comment by cschiller** [comment]
I released a new version. Can you try again with version 5.2.1 and see if you're still experiencing this issue?

**Comment by suuuuz** [comment]
I'm using 5.3.0 and I'm still getting the same mistake. I tried using the extension on another computer and it worked. Maybe I should update Chrome or my Mac?

**Comment by cschiller** [comment]
Hi @suuuuz , I'm not sure exactly what the problem is in your case. It's definitely not necessary for you to update your Mac. The first thing I would do is to make sure you're running the latest version of Chrome (currently 72.0.3626.121). If this is the case I would set up a new profile in Chrome (click on the profile icon near the upper right-hand corner of your browser window and then choose "Manage people"). Then install Zhongwen in the newly created profile. If everything works as expected, then there's some problem with your current Chrome profile.

**Comment by suuuuz** [comment]
I updated my Chrome. For some reason it doesn't notify me its updates. But anyway, the problem is fixed! Thank you so much!

**Comment by cschiller** [comment]
That's great! Enjoy Zhongwen!
