### ISSUE TITLE
Add support to capture the sentence of the word

### ISSUE THREAD

**Issue by p2635** [cschiller/zhongwen#21]
It would be very useful if this could be added. Basically when I save words, I also want to know what the sentence it was in. Perhaps some clever regex stuff might be required to determine what a sentence actually is. Then when I export it, I have a whole list of sentences that can go into Anki.

**Comment by cschiller** [comment]
With version 5.6.0 you can now add notes to the individual entries in the built-in word list. You can paste in the original sentence there.

**Comment by webmagnets** [comment]
> With version 5.6.0 you can now add notes to the individual entries in the built-in word list. You can paste in the original sentence there.

It sure would be nice if it did it automatically.

**Comment by cschiller** [comment]
> It sure would be nice if it did it automatically.

The problem is how to identify the sentences. A lot of web pages contain Chinese text that is not part of a sentence. I think adding the sentence manually is an acceptable compromise.

**Comment by p2635** [comment]
Would a very rough way to do it to simply detect a full stop before and after the target word? Better than nothing right?

**Comment by ExlangBrett** [comment]
> e can discuss
Thanks for getting back to me @cschiller! I don't have the code available as I'm not a developer, but I have graphic design that might help show what I mean. Here is a pdf on my google drive:

https://drive.google.com/file/d/18mlP0zkMRSIVjAaF4ieZxhqGzcYnoCgy/view?usp=sharing

So, the flashcards show the hypothetical that if I was reading on the internet and used the zhongwen plugin to look up two words in the same sentence, "他的歌传遍大街小巷，你会在校园小路、宿舍楼道、人行道、橱窗前以及每一个可以放音乐的大喇叭里听到他的音乐。" The words I might look up are "人行道" and "喇叭".

If we could successfully import the sentence with the vocabulary words then we could simply use the template of the flashcards to create the 14 flashcards in the PDF to allow users to gain fluency with the vocabulary within the context of the sentence they looked them up in.

We could start with just the cards that have the vocabulary words if parsing the sentence turns out to be difficult.

If this idea seems like you might allow it as an addition feature of zhongwen then I'll work on how we might be able to get the code in another branch for you to see.

Thanks,

Brett
