### ISSUE TITLE
ZhongWen not just for browser

### ISSUE THREAD

**Issue by AlxCap83** [cschiller/zhongwen#42]
Hi Christian,
Thank you very much for creating Zhongwen, it is a tool that has helped me a lot over the years.
I just wanted to ask you if you have any plans for developing Zhongwen in a way that it works on EVERY character one comes across (be it PDF, Word, Excel, Mail etc..).
Meaning, is there any way that ZhongWen could work not just on texts appearing within the browser, but everywhere on the computer?
Please let mew know,
Thank you
Alessio

**Comment by cschiller** [comment]
Hi Alessio, unfortunately, because of the way Chrome extensions work, Zhongwen only works on HTML files in a browser. You can, however, convert other documents, like PDF files, to HTML files, using tools that are available on the Internet. You can then use Zhongwen on those converted HTML files. Hope that helps!
